name: Main-Push

# Run this workflow every time a new commit pushed to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
      logLevel:
        description: 'The Logging Level'
        required: false
        default: 'low'

jobs:
  #allow editing of manual running parameters
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Deploy Environment: ${{ github.event.inputs.deployEnvironment }}"
        echo "Log Level: ${{ github.event.inputs.logLevel }}"

  buildx-builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker label info
        id: docklabel
        run: |
          echo "::set-output name=ref::$GITHUB_REF_NAME"
          echo "::set-output name=sha::$GITHUB_SHA"
          echo "::set-output name=repo::$GITHUB_REPOSITORY"
          echo "::set-output name=timestamp::$(date '+%Y%m%d_%H%M%S')"
      -
        name: Show Labels
        run: |
          echo "Ref: ${{ steps.docklabel.outputs.ref }}"
          echo "Sha: ${{ steps.docklabel.outputs.sha }}"
          echo "Repo ${{ steps.docklabel.outputs.repo }}"
          echo "Stamp: ${{ steps.docklabel.outputs.timestamp}}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.docklabel.outputs.repo }}:${{ steps.docklabel.outputs.sha }}
            ghcr.io/${{ steps.docklabel.outputs.repo }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
